### ISSUE TITLE
Locklift Abi.Encode Util

### ISSUE THREAD

**Issue by river-hue** [broxus/locklift#22]
Currently, if I have function that takes a param payload `TvmCell` and I need to encode some inner params in the `TvmCell`, i have to write a separate utility function in the contract to serialize the payload;
```solidity
contract Foo {
     function bar(TvmCell payload) external {
             (address a, uint128 b) = abi.decode(payload, (address, uint128));
             //....
     }
     function utilBar(address a, uint128 b) responsible external returns (TvmCell) {
           return abi.encode(a,b);
     }
}
```
This pattern is generally ok when dealing with one-off serializations, but very inconvenient to deal with when wanting to send custom payloads in the long run. Is there any utility that could be possible to move this to the client side?

**Comment by Rexagon** [comment]
The `provider` object is exposed, so you can use all methods from the [`everscale-inpage-provider`](https://github.com/broxus/everscale-inpage-provider).

- [`packIntoCell`](https://broxus.github.io/everscale-inpage-provider/classes/ProviderRpcClient.html#packIntoCell)
   ```typescript
   let data = await locklift.provider.packIntoCell({
     structure: [
       {name: 'addr', type: 'uint160'},
       {name: 'chainId', type: 'uint32'},
     ] as const, // `as const` is important
     data: {
        addr: evmAddress,
        chainId: evmChainId,
     },
   });
   ```
- [`unpackFromCell`](https://broxus.github.io/everscale-inpage-provider/classes/ProviderRpcClient.html#unpackFromCell)
   ```typescript
   let data = await locklift.provider.unpackFromCell({
     boc,
     structure: [
       {name: 'addr', type: 'uint160'},
       {name: 'chainId', type: 'uint32'},
     ] as const, // `as const` is important
   });
   ```
